// Generated by CoffeeScript 1.6.3
/*
  一张游戏画布，就是一个table。table中的td就相当于一个像素点，点亮td中的div来画画。
         _==/          i     i          \==_
       /XX/            |\___/|            \XX\
     /XXXX\            |XXXXX|            /XXXX\
    |XXXXXX\_         _XXXXXXX_         _/XXXXXX|
   XXXXXXXXXXXxxxxxxxXXXXXXXXXXXxxxxxxxXXXXXXXXXXX
  |XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  |XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|
   XXXXXX/^^^^"\XXXXXXXXXXXXXXXXXXXXX/^^^^^\XXXXXX
    |XXX|       \XXX/^^\XXXXX/^^\XXX/       |XXX|
      \XX\       \X/    \XXX/    \X/       /XX/
         "\       "      \X/      "      /"
*/


(function() {
  var tblHeight, tblWeight, tdHt, tdWt;

  tblHeight = 21;

  tblWeight = 68;

  tdHt = 36;

  tdWt = 25;

  $.fn.extend({
    createMap: function(height, weight) {
      var tblMap, tdCount;
      tblMap = "<table class='base-map'><tbody>";
      while (height--) {
        tdCount = weight;
        tblMap += "<tr>";
        while (tdCount--) {
          tblMap += "<td><div>&nbsp;</div></td>";
        }
        tblMap += "</tr>";
      }
      tblMap += "</tbody></table>";
      return $(this).append(tblMap);
    }
  });

  $(document).ready(function() {
    tblHeight = parseInt($(window).height() / tdHt);
    tblWeight = parseInt($(window).width() / tdWt);
    return $("body").createMap(tblHeight, tblWeight);
  });

}).call(this);

/*
//@ sourceMappingURL=base.map
*/
